<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository
{
}
